config/routes.rb
Rails.application.routes.draw do

  resources :barimages, only: [:create, :destroy]
  resources :frontpage_images, only: [:create, :destroy, :index] do
    member do
      get :toggle_status
    end
  end
  resources :roles, only: [:update]
  resources :bars, except: [:show] do
    member do
      get :remove_top_image
    end
  end
  resources :contactpeople, except: [:show, :index]
  resources :tekniskitems
  resources :tekniskcategories, except: [:new]
  resources :bookingimages, except: [:index, :show, :edit]
  resources :bookings, except: [:show, :index]
  resources :globalsettings, only:[:edit, :update]
  resources :omosses, only:[:edit, :update]
  resources :users, except:[:show]
  
  root 		'pages#home'
  get 		'om-internasjonalen'			        =>	 'pages#about'
  get     'kontakt-internasjonalen'         =>   'pages#kontakt'
  get     'tekniskespsifikasjoner'          =>   'pages#tekniskespsifikasjoner'
  # Endrer "bars" og "bookings" til bar og booking for mer SEO vennelig rute
  get     'bar/:id'                         =>   'bars#show', as: 'bar_show'
  get     'booking/:id'                     =>   'bookings#show', as: 'booking_show'
  # Admin ruter
  get 		'login' 		                      =>	 'sessions#new'
  post		'login' 		                      => 	 'sessions#create'
  delete	'logout'		                      =>	 'sessions#destroy'
  get 		'administrator'	                  =>	 'administrator#index'
  get     'administrator/aldersgrense'      =>   'administrator#aldersgrense'
  get     'administrator/kontaktinfo'       =>   'administrator#kontaktinfo'
  get     'administrator/apningstider'      =>   'administrator#apningstider'
  get     'administrator/hjelp'             =>   'administrator#help'
  get     'administrator/meny'              =>   'administrator#meny'
  get     'administrator/menykategori'      =>   'administrator#menykategori'
  get     'administrator/booking'           =>   'administrator#booking'
  get     'administrator/editbooking'       =>   'administrator#edit_booking'
  get     'administrator/frontpage_images'  =>   'administrator#frontpage_images'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/bar.rb
class Bar < ApplicationRecord
	before_create :create_slug
	has_many :barimages
  mount_uploader :top_image, TopPageImageUploader
  after_commit :remove_top_image!, on: :destroy
  after_commit :remove_previously_stored_top_image, on: :update


  validates :title, presence: true, length: { minimum: 3 }
  validates :seo_description, presence: true, length: { minimum: 5 }
  validates :body, presence: true, length: { minimum: 10 }

  #attr_accessor :top_image
	def create_slug
    	self.slug = self.title.parameterize
  end

  def remove_image
    self.top_image = "Eirik"
  end
end

app/controllers/bars_controller.rb
class BarsController < ApplicationController
  before_action :authenticate_user, except: [:show]
  before_action :set_bar, only: [:edit, :update, :destroy, :remove_top_image]
  before_action :find_bar, only: [:show]


  def remove_top_image
    @bar.top_image.remove!
    redirect_to edit_bar_path(@bar), notice: "Toppbildet er fjernet"
  end
  # GET /bars
  # GET /bars.json
  def index
    @bars = Bar.all
    render layout: 'admin'
  end

  # GET /bars/1
  # GET /bars/1.json
  def show
  end

  # GET /bars/new
  def new
    @bar = Bar.new
    render layout: 'admin'
  end

  # GET /bars/1/edit
  def edit
    @image = Barimage.new
    render layout: 'admin'
  end

  # POST /bars
  # POST /bars.json
  def create
    @bar = Bar.new(bar_params)
      if @bar.save
        redirect_to bars_path, notice: 'Gratulerer med ny bar!'
      else
        render :new, layout: 'admin', notice: 'Husk at en bar må ha et skikkelig navn, Seo Beskrivelse og beskrivelse av etasjen...'
      end
  end

  # PATCH/PUT /bars/1
  # PATCH/PUT /bars/1.json
  def update
      if @bar.update(bar_params)
        redirect_to bars_path, notice: 'Baren er oppdatert'
      else
        redirect_to edit_bar_path(@bar), notice: 'Husk at en bar må ha et skikkelig navn, Seo Beskrivelse og beskrivelse av etasjen...'
      end
  end

  # DELETE /bars/1
  # DELETE /bars/1.json
  def destroy
    @bar.destroy
     redirect_to bars_url, notice: 'Da har baren krympet med en etasje.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_bar
      @bar = Bar.find(params[:id])
    end

    def find_bar
      @bar = Bar.includes(:barimages).find_by_slug(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bar_params
      params.require(:bar).permit(:title, :body, :seo_description, :top_image)
    end
end

app/helpers/bars_helper.rb
module BarsHelper
end

app/views/bars/_add_image.html.haml
.row.mt-4
	.col-12
		= form_for @image do |f|
			- if @image.errors.any? 
				- @image.errors.full_messages.each do |error|
					= alert_generator(error) 
			= f.hidden_field :bar_id, :value => @bar.id
			.row.mt-2
				.col-12
					%h6
						Legg til bilde for baren
					%p.small
						Her kan du legge til flere bilder for å illustrere for gjester hvordan atmosfæren er. Når du legger til et bildet er det krav om en liteb beskrivelse. Navn på fotograf er valgfritt. Prøv å holde bildestrørrelsene ned, men skalering og optimalisering vil serveren ta seg av.
			.row.mt-2
				.col-12
					%label.custom-file
						= f.file_field :image_url, :class => 'custom-file-input'
						%span.custom-file-control
			.row.mt-2
				.col-12
					= f.text_field :description, :class => "form-control", :placeholder => "beskrivelse av bilde"
			.row.mt-2
				.col-12
					= f.text_field :fotograf, :class => "form-control", :placeholder => "fotograf"

			.row.mt-2
				.col-12
					= f.submit 'Legg til', :class => "btn btn-lg btn-block btn-success"
-if @bar.barimages.any?
	.row.mt-4
		- @bar.barimages.each do |image|
			.col-4
				.row
					.col-12.mt-2
						%a{:href => image.image_url, 'data-lightbox' => @bar.title, 'data-title' => image.description}
							= image_tag image.image_url.url(:mobile)
				.row
					.col-12.small.text-muted
						= image.fotograf
				.row
					.col-12.small
						= image.description
				.row
					.col-12
						= link_to image, method: :delete,  data: { confirm: 'Er du sikker?' }, class: "btn btn-sm btn-block btn-danger" do
							%i.fa.fa-trash{"aria-hidden" => "true"}

app/views/bars/_form.html.haml
= form_for @bar do |f|
  - if @bar.errors.any?
    #error_explanation
      %h2= "#{pluralize(@bar.errors.count, "error")} prohibited this bar from being saved:"
      %ul
        - @bar.errors.full_messages.each do |message|
          %li= message
  .row.mt-4
    .col-12
      %strong
        = f.label "Navn på etasjen"
        %br
        %span.small
          (Dette vil også bli navnet på menyelementet)
      = f.text_field :title, :class => "form-control"
  .row.mt-3
    .col-12
      Legg til top bildet (Valgfritt)
      %br
      %label.custom-file
        = f.file_field :top_image, :class => 'custom-file-input'
        %span.custom-file-control
  - if @bar.top_image?
    .row.mt-2
      .col-12
        %img{src: @bar.top_image}
        = link_to "fjern", remove_top_image_bar_path(@bar), class: "btn btn-danger btn-sm"
  .row
    .col-12
  .row.mt-3
    .col-12.pt-3
      %strong
        = f.label "SEO beskrivelse"
      %br
      %span.small
        Beskrivelsen her vil gå i headeren på siden som igjen blir plukket opp av søkemotorer. For at denne skal være optimal, er det fint om teksten her holdes til 160 tegn
        = link_to "Mer informasjon her", administrator_hjelp_path(anchor: "seoingress")
      = f.text_area :seo_description, :id => 'seodescription', :class => 'form-control'
  .row
    .col-12#seodescriptionfeedback.text-muted.text-right
      Tegn igjen:
      %span#seodescriptioncount
        160
  .row.mt-2
    .col-12
      %strong
        = f.label "beskrivelse av etasjen"
      = f.cktext_area :body, :class => "form-control"
  .row.mt-4
    .col-6
      = link_to bars_path do
        %button.btn.btn-warning.btn-block
          %i.fa.fa-reply{"aria-hidden" => "true"}
          Tilbake
    .col-6
      = f.submit 'Save', :class => "btn btn-success btn-block"

app/views/bars/edit.html.haml
.row.justify-content-center.mt-4
	.col-12.col-md-10.col-lg-5
		%h1
			Edit
			= @bar.title
	.row
		.col-12.col-lg-5
			= render 'bars/add_image'
		.col-12.col-lg-6.offset-lg-1
			= render 'form'

app/views/bars/index.html.haml
.container
  .row.justify-content-center
    .col-md-8.col-lg-6.col-12
      .row.mt-4
        .col-12.text-center
          %h2
            Bar
      .row.mt-4
        .col-12.small
          -if @bars.nil?
            Når det ikke er lag til noen barer/etasjer må du først gjøre dette. Titelen på vil dukke opp i menyen på hovedsiden.
          -else
            Her kan du klikke og endre informasjonen om etasjene legge til eller slette.
      - @bars.each do |bar|
        .row.mt-3
          .col-10
            = link_to edit_bar_path(bar) do
              %button.btn.btn-info.btn-block
                = bar.title
          .col-2
            = link_to bar, method: :delete, data: { confirm: 'Er du sikker?' } do
              %button.btn.btn-warning.btn-block
                %i.fa.fa-trash{"aria-hidden" => "true"}
      .row.mt-3
        .col-12
          = link_to new_bar_path do
            %button.btn.btn-success.btn-block
              %i.fa.fa-plus{"aria-hidden" => "true"}
              Legg til etasje..ehhh..Bar...
      .row.mt-3
        .col-12
          = link_to administrator_path do

            %button.btn.btn-warning.btn-block
              %i.fa.fa-reply{"aria-hidden" => "true"}
              Tilbake

app/views/bars/new.html.haml
.row.justify-content-center.mt-4
	.col-12.col-md-10.col-lg-5
		%h1
			Ny bar
		= render 'form'

app/views/bars/show.html.haml
-provide(:description, "Beskrivelse")
-provide(:title, "Vår spennende #{@bar.title}")
-provide(:canonical, "/bar/#{@bar.slug}")
%section.container.mt-4.mb-4
	%article.row.justify-content-center.mb-2		
		.col-10
			%h2.pb-4.pt-4
				= @bar.title.upcase
			-if @bar.top_image?
				%img{src: @bar.top_image, alt: "internasjonalen Oslo - #{@bar.title}"}
			%p
				= @bar.body.html_safe
	%aside.row.justify-content-center
		.col-10
			.row.mb-4.pb-3
				- @bar.barimages.each do |i|
					.col-6.col-md-4.col-lg-3.mt-1
						%a{:href => i.image_url.url, 'data-lightbox' => @bar.title, 'data-title' => i.description}
							= image_tag i.image_url.url(:mobile), alt: "Internasjonalen Oslo - #{i.description}"