config/routes.rb
Rails.application.routes.draw do

  resources :barimages, only: [:create, :destroy]
  resources :frontpage_images, only: [:create, :destroy, :index] do
    member do
      get :toggle_status
    end
  end
  resources :roles, only: [:update]
  resources :bars, except: [:show] do
    member do
      get :remove_top_image
    end
  end
  resources :contactpeople, except: [:show, :index]
  resources :tekniskitems
  resources :tekniskcategories, except: [:new]
  resources :bookingimages, except: [:index, :show, :edit]
  resources :bookings, except: [:show, :index]
  resources :globalsettings, only:[:edit, :update]
  resources :omosses, only:[:edit, :update]
  resources :users, except:[:show]
  
  root 		'pages#home'
  get 		'om-internasjonalen'			        =>	 'pages#about'
  get     'kontakt-internasjonalen'         =>   'pages#kontakt'
  get     'tekniskespsifikasjoner'          =>   'pages#tekniskespsifikasjoner'
  # Endrer "bars" og "bookings" til bar og booking for mer SEO vennelig rute
  get     'bar/:id'                         =>   'bars#show', as: 'bar_show'
  get     'booking/:id'                     =>   'bookings#show', as: 'booking_show'
  # Admin ruter
  get 		'login' 		                      =>	 'sessions#new'
  post		'login' 		                      => 	 'sessions#create'
  delete	'logout'		                      =>	 'sessions#destroy'
  get 		'administrator'	                  =>	 'administrator#index'
  get     'administrator/aldersgrense'      =>   'administrator#aldersgrense'
  get     'administrator/kontaktinfo'       =>   'administrator#kontaktinfo'
  get     'administrator/apningstider'      =>   'administrator#apningstider'
  get     'administrator/hjelp'             =>   'administrator#help'
  get     'administrator/meny'              =>   'administrator#meny'
  get     'administrator/menykategori'      =>   'administrator#menykategori'
  get     'administrator/booking'           =>   'administrator#booking'
  get     'administrator/editbooking'       =>   'administrator#edit_booking'
  get     'administrator/frontpage_images'  =>   'administrator#frontpage_images'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/partials/_footer.html.haml
%footer.container-fluid.bg-light.pb-4{"data-turbolinks-permanent" => true}
	.container
		.row.ml-0.mr-0.justify-content-between.pt-3
			.card.col-12.col-md-5.mb-3
				.card-body
					.card-title
						%h4
							Åpningstider
					.card-text		
						- if @setting.mandag?
							%meta{:itemprop => "openingHours", :content => 'Mo '+@setting.mondayopens+'-'+@setting.mondaycloses}
						- if @setting.tirsdag?
							%meta{:itemprop => "openingHours", :content => 'Tu '+@setting.tuesdayopens+'-'+@setting.tuesdaycloses}
						- if @setting.onsdag?
							%meta{:itemprop => "openingHours", :content => 'We '+@setting.wednesdayopens+'-'+@setting.wednesdaycloses}
						- if @setting.torsdag?
							%meta{:itemprop => "openingHours", :content => 'Th '+@setting.thursdayopens+'-'+@setting.thursdaycloses}
						- if @setting.fredag?
							%meta{:itemprop => "openingHours", :content => 'Fr '+@setting.fridayopens+'-'+@setting.fridaycloses}
						- if @setting.lørdag?
							%meta{:itemprop => "openingHours", :content => 'Sa '+@setting.saturdayopens+'-'+@setting.saturdaycloses}
						- if @setting.søndag?
							%meta{:itemprop => "openingHours", :content => 'Su '+@setting.sundayopens+'-'+@setting.sundaycloses}
						= @setting.openingtimes.html_safe
						.col-12.text-right.p-0
							Aldersgrense:
							%strong
								=@setting.aldersgrense
							år
			%address.card.col-12.col-md-5
				.card-body
					.card-title
						%h4
							Adresse
					.card-text
						.row.mt-3
							.col-lg-4.col-12{:itemprop => "address", :itemscope => true, :itemtype => "http://schema.org/PostalAddress"}
								%span{:itemprop => "streetAddress"}
									= @setting.adresse
								%br
								%span{:itemprop => "postalCode"}
									= @setting.postnr
								\
								%span{:itemprop => "addressRegion"}
									= @setting.poststed
							.col-lg-8.col-12
								%span{:itemprop => "email"}
									= mail_to @setting.epost, encode: "hex", class: "contactmail" do
										= email_robot(@setting.epost)
								%br
								%span{:itemprop => "telephone"}
									(+47)
									%a{:href => "tel:#{@setting.telefonnr}"}
										= @setting.telefonnr
	.row.justify-content-center.mt-4
		.col-10.text-center
			= render 'partials/some'
	.row
		.col-12#map{:image => "#{image_url('marker.png')}"}
	.row.pb-2.text-center.mt-3
		.col-12.credit
			2017 - #{Time.now.year} 
			%a.credit{:href => "http://www.reelmedianordic.com/", :target => "_blank"}
				@reelmedianordic
	

app/views/partials/_google.html.erb
<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-109333075-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-109333075-1');
</script>

app/views/partials/_hamburger.html.haml
%section
	.icon.menu1.mobile
		%span
		%span
		%span

app/views/partials/_header.html.haml
%header.container-fluid.bg-light{"data-turbolinks-permanent" => true}
	.container
		.row.justify-content-between
			.col-4.col-sm-3.col-md-2.col-lg-2.col-#logo.pb-2
				= link_to root_path do
					%img{:src => asset_url('interlogorod.svg'), :type => "image/svg+xml", :itemprop => "logo", :alt => "Internasjonalen logo"}
			.col-4.text-right.p-0.pt-3
				= render 'partials/hamburger'
			.col-auto.d-none.align-content-right
				%nav{:role => 'navigation'}
					= render 'partials/mainmenu'
		%nav.container.lukket.bg-light#mobilemenu.pt-4.pb-2{:role => "Navigation"}
			.row
				.col-12
					= render 'partials/mobilemenu'

app/views/partials/_kontakt_person.html.haml
%h3
  = titel
.row.pt-2.pb-4
  .col-10
    %h5
      %i.fa.fa-user{"aria-hidden" => "true"}
      = person.name
      %small
        \-
        = contact_rolle person.stilling
    %p
      %i.fa.fa-envelope-o{"aria-hidden" => "true"}
      = mail_to person.email, encode: "hex", class: "contactmail" do
        = email_robot(person.email)
    - if person.showtelefon?
      %p
        %i.fa.fa-phone{"aria-hidden" => "true"}
        (+47)
        %a{:href => "tel:#{person.telefon}"}
          = person.telefon
        \//
        %a{:href => "sms://#{person.telefon}"}
          %i.fa.fa-comments{"aria-hidden" => "true"}
          Send en melding

app/views/partials/_mainmenu.html.haml
#mainmenu
	= link_to om_internasjonalen_path do
		.menu
			Om oss
	- if @bars.any?
		.menu.dropdown
			Bar
			%i.fa.fa-caret-down{"aria-hidden" => "true"}
			.dropdown-content
				- @bars.each do |b|
					= link_to bar_show_path(b.slug) do
						= b.title
	- if @bookings.any?
		.menu.dropdown
			Booking
			%i.fa.fa-caret-down{"aria-hidden" => "true"}
			.dropdown-content
				- @bookings.each do |c|
					= link_to booking_show_path(c.slug) do
						= c.title
				= link_to tekniskespsifikasjoner_path do
					Tekniske spesifikasjoner
	= link_to kontakt_internasjonalen_path do	
		.menu
			Kontakt

app/views/partials/_mobilemenu.html.haml
%nav.bg-light
	.row.justify-content-center
		.col-10.col-md-4.text-left.pt-4
			%h5
				Internasjonalen
			%ul
				%li
					= link_to om_internasjonalen_path do
						Om oss
				%li
					= link_to kontakt_internasjonalen_path do
						Kontakt
		.col-10.col-md-4.pt-4
			%h5
				Bar
			%ul
				- @bars.each do |b|
					%li
						= link_to b.title, bar_show_path(b.slug)	
		.col-10.col-md-8.text-left.pt-4.pb-4
			%h5
				Booking
			%ul
				- @bookings.each do |c|
					%li
						= link_to c.title, booking_show_path(c.slug)
				= link_to tekniskespsifikasjoner_path do
					%li
						Tekniske spesifikasjoner
			

app/views/partials/_page_static_home.html.haml
.jumbotron
	.row
		.col-12
			%h1.mt-3.text-center.text-white
				= @setting.slogan.upcase
	.row
		.col-12.text-center
			%a{:href => "https://www.google.com/maps/place/Internasjonalen/@59.9141892,10.7487952,419m/data=!3m1!1e3!4m13!1m7!3m6!1s0x0:0x0!2zNDXCsDI3JzUxLjAiTiA5wrAxMScyOS4wIkU!3b1!8m2!3d45.464167!4d9.191389!3m4!1s0x0:0x2f311a016cc4580a!8m2!3d59.9145319!4d10.7495843?hl=no" , :target => "_blank"}
				%button.btn.btn-success.btn-lg.mt-2
					%i.fa.fa-location-arrow{"aria-hidden" => "true"}
					Finn veien for meg!
			= link_to "Kontakt Oss", kontakt_internasjonalen_path, class:"btn btn-lg btn-light mt-2"

app/views/partials/_some.html.haml
.row
	.col-12
		%h5
			Følg oss på sosiale medier:
.row.justify-content-center.somefooter
	.col-2.m-4
		%a{:href => "https://www.facebook.com/internasjonalenbar/", target: "_blank"}
			%i.fa.fa-facebook{"aria-hidden" => "true"}
	.col-2.m-4
		%a{:href => "https://twitter.com/internasjon_bar", target: "_blank"}
			%i.fa.fa-twitter{"aria-hidden" => "true"}
	.col-2.m-4
		%a{:href => "https://www.instagram.com/internasjonalen/", target: "_blank"}
			%i.fa.fa-instagram{"aria-hidden" => "true"}