config/routes.rb
Rails.application.routes.draw do

  resources :barimages, only: [:create, :destroy]
  resources :frontpage_images, only: [:create, :destroy, :index] do
    member do
      get :toggle_status
    end
  end
  resources :roles, only: [:update]
  resources :bars, except: [:show] do
    member do
      get :remove_top_image
    end
  end
  resources :contactpeople, except: [:show, :index]
  resources :tekniskitems
  resources :tekniskcategories, except: [:new]
  resources :bookingimages, except: [:index, :show, :edit]
  resources :bookings, except: [:show, :index]
  resources :globalsettings, only:[:edit, :update]
  resources :omosses, only:[:edit, :update]
  resources :users, except:[:show]
  
  root 		'pages#home'
  get 		'om-internasjonalen'			        =>	 'pages#about'
  get     'kontakt-internasjonalen'         =>   'pages#kontakt'
  get     'tekniskespsifikasjoner'          =>   'pages#tekniskespsifikasjoner'
  # Endrer "bars" og "bookings" til bar og booking for mer SEO vennelig rute
  get     'bar/:id'                         =>   'bars#show', as: 'bar_show'
  get     'booking/:id'                     =>   'bookings#show', as: 'booking_show'
  # Admin ruter
  get 		'login' 		                      =>	 'sessions#new'
  post		'login' 		                      => 	 'sessions#create'
  delete	'logout'		                      =>	 'sessions#destroy'
  get 		'administrator'	                  =>	 'administrator#index'
  get     'administrator/aldersgrense'      =>   'administrator#aldersgrense'
  get     'administrator/kontaktinfo'       =>   'administrator#kontaktinfo'
  get     'administrator/apningstider'      =>   'administrator#apningstider'
  get     'administrator/hjelp'             =>   'administrator#help'
  get     'administrator/meny'              =>   'administrator#meny'
  get     'administrator/menykategori'      =>   'administrator#menykategori'
  get     'administrator/booking'           =>   'administrator#booking'
  get     'administrator/editbooking'       =>   'administrator#edit_booking'
  get     'administrator/frontpage_images'  =>   'administrator#frontpage_images'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/administrator_controller.rb
class AdministratorController < ApplicationController
	before_action :authenticate_user
	layout 'admin'
  	def index
  	end

  	def aldersgrense

  	end

  	def kontaktinfo
      @contactpeople = Contactperson.all
      @contactperson = Contactperson.new
      @role = Role.find(1)
  	end

  	def apningstider
  		
  	end

    def help
      
    end

    def frontpage_images
      @frontpage_images = FrontpageImage.all
      @frontpageImage = FrontpageImage.new
    end

    def booking
      @bookings = Booking.all
      @contactpeople = Contactperson.all
      @role = Role.find(2)
    end

    def edit_booking
      @booking = Booking.find(params[:id])
      @image = Bookingimage.new
      @images = Bookingimage.where(bookings_id: @booking.id).all
    end

    def meny
      @category = Category.all
    end

    def menykategori
      @drinks = Drink.where(category_id: params[:id] )
    end

  	private	

end

app/helpers/administrator_helper.rb
module AdministratorHelper

  
end

app/views/administrator/aldersgrense.html.haml
.container
	.row.justify-content-center
		.col-12.col-md-8.col-lg-6
			= form_for @setting do |f|
				.row.mt-4
					.col-7.pt-2
						%h2
							Aldersgrense
						.input-group
							=f.number_field :aldersgrense, :class => "form-control", 'aria-describedby' =>  "aar"
							%span.input-group-addon#aar
								år

				.row.mt-3
					.col-12.pt-2
						= link_to administrator_path do
							%button.btn.btn-warning
								%i.fa.fa-reply{"aria-hidden" => "true"}
								Tilbake
						= f.submit 'Lagre', :class => 'btn btn-success'
	

app/views/administrator/apningstider.html.haml
.container
	.row.mt-3.justify-content-center
		%h3
			Åpningstider

	= form_for @setting do |f|
		.row.mt-3#apningstider.justify-content-center
			.col-12.col-md-8.col-lg-6.form-check.mb-2
				.row
					.col-12

						%p.small
							Boksen til venstre hukes av om det er åpent på aktuelle dagen. Ellers føres åpnings og lukketider inn for hver dag. Serveren vil slå sammen dager med like åpningstider og sette dette sammen på riktig måte.
						%p.small
							Lurer du på flere ting vedrørende administrasjonssiden kan du finne 
							= link_to "mer informasjon her", administrator_hjelp_path
				.row.p-1.pt-2.pb-3.bg-light.text-dark.justify-content-between
					.col-1 
						= f.check_box :mandag, {:id => "mondayopen"}, 'true' , 'false'
					.col-3
						Mandag
					.d-flex.mondaytime
						= f.number_field :mandaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :mandagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.mondaytime
						= f.number_field :mandagclosinghour , min: 0, max: 23, :class => "apningstider"
						\ : 
						= f.number_field :mandagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-white.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :tirsdag, {:id => "tuesdayopen"}, 'true' , 'false'
					.col-3
						Tirsdag
					.d-flex.tuesdaytime
						= f.number_field :tirsdaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :tirsdagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.tuesdaytime
						= f.number_field :tirsdagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :tirsdagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-light.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :onsdag, {:id => "wednesdayopen"}, 'true' , 'false'
					.col-3
						Ondag
					.d-flex.wednesdaytime
						= f.number_field :onsdaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :onsdagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.wednesdaytime
						= f.number_field :onsdagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :onsdagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-white.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :torsdag, {:id => "thursdayopen"}, 'true' , 'false'
					.col-3
						Torsdag
					.d-flex.thursdaytime
						= f.number_field :torsdaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :torsdagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.thursdaytime
						= f.number_field :torsdagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :torsdagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-light.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :fredag, {:id => "fridayopen"}, 'true' , 'false'
					.col-3
						Fredag
					.d-flex.fridaytime
						= f.number_field :fredaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :fredagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.fridaytime
						= f.number_field :fredagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :fredagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-white.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :lørdag, {:id => "saturdayopen"}, 'true' , 'false'
					.col-3
						Lørdag
					.d-flex.saturdaytime
						= f.number_field :lørdaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :lørdagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.saturdaytime
						= f.number_field :lørdagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :lørdagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.p-1.bg-light.text-dark.pt-2.pb-3.justify-content-between
					.col-1
						= f.check_box :søndag, {:id => "sundayopen"}, 'true' , 'false'
					.col-3
						Søndag
					.d-flex.sundaytime
						= f.number_field :søndaghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :søndagminute , min: 0, max: 59, :class => "apningstider"
					.col-1.mondaytime.text-left
						\
					.d-flex.sundaytime
						= f.number_field :søndagclosinghour , min: 0, max: 23, :class => "apningstider"
						\:
						= f.number_field :søndagclosingminute , min: 0, max: 59, :class => "apningstider"
				.row.mt-3
					.col-6
						= link_to :back do
							%button.btn.btn-warning.btn-lg.btn-block
								%i.fa.fa-reply{"aria-hidden" => "true"}
								Tilbake
					.col-6
						= f.submit 'lagre', :class => "btn btn-outline-success btn-lg btn-block"

app/views/administrator/booking.html.haml
.container
	.row.justify-content-center
		.col-md-8.col-lg-6.col-12
			.row.mt-4
				.col-12.text-center
					%h2
						Booking
			.row.mt-3
				.col-12
					= form_for @role, :url => role_path(@role.id),:html => {:method => :put} do |f|
						%h5
							Bookingansvalig:
						= f.select(:contactperson_id, [['Ingen', 0]] + @contactpeople.collect{|c| [c.name, c.id]}, {}, {class: 'custom-select'})
						%button.btn.btn-primary{:type => 'submit'}
							%i.fa.fa-floppy-o{"aria-hidden" => "true"}
						=link_to new_contactperson_path do
							%button.btn.btn-success
								%i.fa.fa-plus{"aria-hidden" => "true"}
								%i.fa.fa-user{"aria-hidden" => "true"}
			- @bookings.each do |b|
				.row.mt-3
					.col-9
						= link_to administrator_editbooking_path(:id => b.id) do
							%button.btn.btn-info.btn-sm.btn-block
								= b.title
					.col-3
						= link_to b, method: :delete, data: { confirm: 'Er du sikker?' } do
							%button.btn.btn-danger.btn-sm.btn-block.text-center
								%i.fa.fa-trash.animated.tada{"aria-hidden" => "true"}
			.row.mt-3
				.col-12
					= link_to tekniskcategories_path do
						%button.btn.btn-info.btn-sm.btn-block
							%i.fa.fa-cog.fa-spin{"aria-hidden" => "true"}
							Tekniske spesifikasjoner
			.row.mt-3
				.col-12
					= link_to new_booking_path do
						%button.btn.btn-outline-success.btn-sm.btn-block
							%i.fa.fa-pluss{"aria-hidden" => "true"}
							Nytt booking objekt

			.row.mt-3
				.col-12
					= link_to administrator_path do
						%button.btn-warning.btn.btn-block.btn-sm
							%i.fa.fa-reply{"aria-hidden" => "true"}
							Tilbake

app/views/administrator/edit_booking.html.haml
.row.mt-4.justify-content-center
	.col-12.col-md-10.col-lg-6.mt-4
		%h1
			= @booking.title
		%p
			=link_to edit_booking_path(@booking) do
				%i.fa.fa-edit{"aria-hidden" => "true"}
				Rediger #{@booking.title.downcase}
.row.mt-4.justify-content-center
	.col-10.col-md-10.col-lg-6
		.row.mt-2
			- @images.each do |i|
				.col-6.col-md-4.col-lg-3.mt-1
					.row
						.col-12
							%a{:href => i.image.url, 'data-lightbox' => @booking.title, 'data-title' => i.description}
								= image_tag i.image.url(:mobile)
					.row
						.col-12.small
							%em
								= i.description
					.row
						.col-12
							%small
								%em
								%strong
									Foto:
								= i.fotograf
					.row.justify-content-left
						.col-3
							%div{'data-toggle' => 'modal', 'data-target' => "##{i.description.parameterize}" }
								%i.fa.fa-edit{"aria-hidden" => "true"}
						.col-3
							=link_to i, method: :delete, data: { confirm: 'Are you sure?' } do
								%i.fa.fa-trash{"aria-hidden" => "true"}
				.modal.fade{:id => i.description.parameterize, :tabindex => '-1', :role => "dialog", 'aria-labelledby' =>i.description.parameterize + i.id.to_s, 'aria-hidden' => 'true' }
					.modal-dialog{:role => 'document'}
						.modal-content
							= form_for i do |f|
								.modal-header
									%h6.modal-title{:id => "#{i.description.parameterize}-title"}
										Rediger bilde
									%button.close{:type => "button", 'data-dismiss' => 'modal', 'aria-label' => 'close'}
										%span{ 'aria-hidden' => 'true'} 
											&times; 
								.modal-body
									.row.mt-2
										.col-12
											= f.text_field :description, :class => "form-control", :placeholder => "beskrivelse av bilde"
									.row.mt-2
										.col-12
											= f.text_field :fotograf, :class => "form-control", :placeholder => "fotograf"
								.modal-footer
									= f.submit 'Lagre endringer', :class => "btn-success btn"
									%button.btn.btn-secondary{:type => 'button', 'data-dismiss' => 'modal'}
										Lukk
.row.mt-4.justify-content-center
	.col-12.col-md-10.col-lg-6.mt-4
		%h4
			Legg til bilde
		%p.small
			Her kan du legge til flere bilder for å illustrere for gjester hvordan atmosfæren er. Når du legger til et bildet er det krav om en liteb beskrivelse. Navn på fotograf er valgfritt. Prøv å holde bildestrørrelsene ned, men skalering og optimalisering vil serveren ta seg av.
.row.justify-content-center
	.col-12.col-md-10.col-lg-6
		= form_for @image do |f|
			- if @booking.errors.any? 
				- @booking.errors.full_messages.each do |error|
					= alert_generator(error) 
			= f.hidden_field :bookings_id, :value => @booking.id
			.row.mt-2
				.col-12
					%label.custom-file
						= f.file_field :image, :class => 'custom-file-input'
						%span.custom-file-control
			.row.mt-2
				.col-12
					= f.text_field :description, :class => "form-control", :placeholder => "beskrivelse av bilde"
			.row.mt-2
				.col-12
					= f.text_field :fotograf, :class => "form-control", :placeholder => "Fotograf (valgfritt)"

			.row.mt-2
				.col-12
					= f.submit 'Legg til', :class => "btn btn-lg btn-block btn-success"

.row.mt-4.justify-content-center
	.col-12.col-md-10.col-lg-6.mt-4
		= link_to administrator_booking_path do
			%button.btn.btn-lg.btn-warning.btn-block
				%i.fa.fa-reply{"aria-hidden" => "true"}				
				Tilbake

app/views/administrator/frontpage_images.html.haml
.row.justify-content-center
  .col-md-8.col-lg-6.col-12
    .row.mt-4
      .col-12
        %h1
          Forside bilder
        %p.small
          Her kan du laste opp bilder som blir brukt til en bilde karusell på forsiden. Kravet er at to bilder er lastet opp og er publisert. Når to bilder er lastet opp starter karusellen av seg selv. Prøv å holde bildestrørrelsene ned, men skalering og optimalisering vil serveren ta seg av.
    .row
      .col-12
        = form_for(@frontpageImage) do |f|
          - if @frontpageImage.errors.any?
            #error_explanation
              %h2= "#{pluralize(@frontpageImage.errors.count, "error")} prohibited this booking from  being saved:"
              %ul
                - @frontpageImage.errors.full_messages.each do |message|
                  %li= message

          .row.mt-3
            .row
              .d-flex.ml-3
                %label.custom-file
                  = f.file_field :image_url, :class => 'custom-file-input'
                  %span.custom-file-control
              .d-flex.ml-3
                %button.btn.btn-success.btn-block{:type => "submit"}
                  %i.fa.fa-floppy-o{"aria-hidden" => "true"}
    - if @frontpage_images.count > 0 && @frontpage_images.count < 2
      .row.mt-4
        .col-12
          .alert.alert-warning
            %i.fa.fa-info-circle{"aria-hidden" => "true"}
            Hei! Bra at du har lagt til et bilde. Men et bilde gjør ingen karusell... Så for at vi skal kunne stare å snurre bilder, må du legge til en til.

    .row.mt-4
      -if @frontpage_images.any?
        %table.table
          %thead
            %tr
              %th
                \#
              %th{width: 100, scope: 'col'}
                Bilde
              %th{scope: 'col'}
                Status
              %th{scope: 'col'}
          %tbody
            - @frontpage_images.each_with_index do |i,x|
              %tr
                %td{scope: "row"}
                  = x+1
                %td
                  = image_tag(i.image_url)
                %td{ class: "#{i.status}"}
                  = image_status i.status
                %td.text-right
                  = link_to image_btn(i) , toggle_status_frontpage_image_path(i), class:"btn #{image_btn_style(i)}"

                %td.text-right
                  = link_to i, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger" do
                    %i.fa.fa-trash{"aria-hidden" => "true"}
      -else
        .col-12
          .alert.alert-warning
            %i.fa.fa-info-circle{"aria-hidden" => "true"}
            Det er ikke lagt inn noen forside bilder enda. Siden bruker nå default bilde
    .row.mt-3
      .col-12
        = link_to administrator_path do
          %button.btn-warning.btn.btn-block.btn-sm
            %i.fa.fa-reply{"aria-hidden" => "true"}
            Tilbake

app/views/administrator/index.html.haml
.row.justify-content-center
	.col-md-8.col-lg-6.col-12
		.row.pt-2.justify-content-between
			.col-12.small.text-secondary.font-weight-light.mt-3
				%i.fa.fa-user{"aria-hidden" => "true"}
				#{current_user.name}
				|
				%i.fa.fa-calendar{"aria-hidden" => "true"} 
				= Time.now.strftime("%d/%m/%Y")
			.col-12.text-right.mt-3
				= link_to logout_path, method: :delete do
					%button.btn.btn-outline-danger.btn-sm
						%i.fa.fa-sign-out{"aria-hidden" => "true"}
						logg ut
				= link_to administrator_hjelp_path do
					%button.btn.btn-outline-primary.btn-sm
						%i.fa.fa-ambulance{"aria-hidden" => "true"}
						Hjelp!
		.row.pt-3
			.col-12
				= link_to administrator_apningstider_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Åpningstider
		.row.pt-3
			.col-12
				= link_to edit_omoss_path(@about) do
					%button.btn.btn-secondary.btn-block.btn-lg
						Om oss
		.row.pt-3
			.col-12
				= link_to bars_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Bar
		.row.pt-3
			.col-12
				= link_to administrator_booking_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Booking
		.row.pt-3
			.col-12
				= link_to administrator_aldersgrense_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Aldersgrense
		.row.pt-3
			.col-12
				= link_to administrator_kontaktinfo_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Kontaktinformasjon
		.row.pt-3
			.col-12
				= link_to administrator_frontpage_images_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Forsidebilder
		.row.pt-3
			.col-12
				= link_to users_path do
					%button.btn.btn-secondary.btn-block.btn-lg
						Bruker
					

app/views/administrator/kontaktinfo.html.haml
.container
	.row.justify-content-center
		.col-12.col-md-8.col-lg-6
			= form_for @setting do |f|
				.row.mt-3
					.col-12
						= f.text_field :adresse, :class => "form-control", :placeholder => 'Sett gatenavn og nummer'
				.row.justify-content-between.mt-3
					.col-5
						= f.text_field :postnr, :class => "form-control", :placeholder => 'Postnr'
					.col-5
						= f.text_field :poststed, :class => "form-control", :placeholder => 'poststed'
				.row.mt-3
					.col-12.input-group.input-group-lg
						%span#email.input-group-addon
							@
						= f.email_field :epost, :class => "form-control", "aria-describedby" => "email"
				.row.mt-3
					.col-12.input-group.input-group-lg
						%span#phone.input-group-addon
							+47
						= f.telephone_field :telefonnr, :class => "form-control", "aria-describedby" => "phone"
				.row.mt-3
					.col-12
						%strong
							= f.label "Slagord:"
						= f.text_field :slogan, class: "form-control"
				.row.mt-3
					.col-12.pt-2
						= f.submit 'Lagre', :class => 'btn btn-success btn-block'
				-if @contactpeople.any?
					.row.mt-3
						.col-12.pt-2
							%h4
								Sett daglig leder
	.row.justify-content-center
		.col-12.col-md-8.col-lg-6
			= form_for @role, :url => role_path(@role.id),:html => {:method => :put} do |r|
				.row
					.col-12.pt-2
						= r.select(:contactperson_id, [['Ingen', 0]] + @contactpeople.collect{|c| [c.name, c.id]}, {include_blank: "Velg Kontaktperson" , }, {class: 'custom-select'})
						= r.submit 'Lagre', :class => 'btn btn-success'

				- if @contactpeople.any?
					.row.mt-3
						.col-12
							%h4
								Kontaktpersoner
						%table.table
							%thead.dark
								%tr
									%th
										Navn
									%th
										Posisjon
									%th
							%tbody
								- @contactpeople.each do |cp|							
									%tr
										%td
											%small
												= cp.name
										%td
											%small
												= contact_rolle cp.stilling
										%td
											= link_to edit_contactperson_path(cp) do
												%i.fa.fa-edit{"aria-hidden" => "true"}
											= link_to cp, method: :delete, data: { confirm: 'Are you sure?' } do
												%i.fa.fa-trash{"aria-hidden" => "true"}
				.row.mt-3
					.col-12
						= link_to new_contactperson_path do
							%button.btn.btn-block.btn-outline-success
								%i.fa.fa-plus{"aria-hidden" => "true"}
								Legg til kontaktperson


				.row.mt-2
					.col-12
						= link_to administrator_path do
							%button.btn.btn-warning.btn-block
								%i.fa.fa-reply{"aria-hidden" => "true"}
								Tilbake

app/views/administrator/meny.html.haml
.container
	.row.justify-content-center
		.col-md-8.col-lg-6.col-12
			.row.mt-4
				.col-12.text-center
					%h2
						Meny
			.row.mt-3
				.col-12
					- @category.each do |c|
						.row.mt-3
							.col-12
								=link_to administrator_menykategori_url(:id => c.id) do
									%button.btn-info.btn-lg.btn.btn-block
										= c.title
			.row.mt-3
				.col-12
					= link_to new_category_path do
						%button.btn-outline-success.btn.btn-block.btn-lg
							%i.fa.fa-plus{"aria-hidden" => "true"}
							Ny meny kategory
			.row.mt-3
				.col-12
					= link_to administrator_path do
						%button.btn-warning.btn.btn-block.btn-lg
							%i.fa.fa-reply{"aria-hidden" => "true"}
							Tilbake

app/views/administrator/menykategori.html.haml
.row.justify-content-center
	.col-md-8.col-lg-6.col-12
		.row.mt-4
			.col-12
				%h1
					= @kategori.title
				%small
					= link_to edit_category_path(@kategori) do
						%i.fa.fa-edit{"aria-hidden" => "true"}
						Rediger #{@kategori.title}
		.row.mt-3
			.col-12
				= link_to new_drink_path do
					%button.btn.btn-lg.btn-success.btn-block
						%i.fa.fa-plus{"aria-hidden" => "true"}
						Legg til ny drink
		.row.mt-1.justify-content-start
			.col-4
				= link_to administrator_meny_path do
					%button.btn.btn-sm.btn-warning.btn-block
						%i.fa.fa-reply{"aria-hidden" => "true"}
						Tilbake
		.row.mt-1
			.col-12
				-if @drinks.any?
					%table.table
						%thead
							%tr
								%th 
									Navn
								%th
									Valg
								%th
						%tbody   
							- @drinks.each do |d|
								%tr
									%td{width: "60%"}
										= d.title
									%td
										= link_to edit_drink_path(d) do
											%i.fa.fa-edit{"aria-hidden" => "true"}
											Rediger
									%td
										= link_to d, method: :delete, data: { confirm: 'Are you sure?' } do
											%i.fa.fa-trash{"aria-hidden" => "true"}
											Slett
							
							
								

app/views/administrator/utleietext.html.haml
.container
	.row.justify-content-center
		.col-md-8.col-lg-6.col-12
			.row.mt-4
				.col-12.text-center
					%h2
						Utleie text
			.row.mt-3
				.col-12
					= form_for @utleie do |f|
						- if @utleie.errors.any?
							#error_explanation
								%h2= "#{pluralize(@utleie.errors.count, "error")} prohibited this utleie from being saved:"
								%ul
									- @utleie.errors.full_messages.each do |message|
										%li= message
						.row
							.col-12.pt-3
								= f.cktext_area :ingress
						.row
							.col-6.pt-3
								= link_to :back do
									%button.btn.btn-warning.btn-block
										%i.fa.fa-reply{"aria-hidden" => "true"}
										Tilbake
							.col-6.pt-3
								= f.submit 'Lagre', :class => 'btn btn-success btn-block'