config/routes.rb
Rails.application.routes.draw do

  resources :barimages, only: [:create, :destroy]
  resources :frontpage_images, only: [:create, :destroy, :index] do
    member do
      get :toggle_status
    end
  end
  resources :roles, only: [:update]
  resources :bars, except: [:show] do
    member do
      get :remove_top_image
    end
  end
  resources :contactpeople, except: [:show, :index]
  resources :tekniskitems
  resources :tekniskcategories, except: [:new]
  resources :bookingimages, except: [:index, :show, :edit]
  resources :bookings, except: [:show, :index]
  resources :globalsettings, only:[:edit, :update]
  resources :omosses, only:[:edit, :update]
  resources :users, except:[:show]
  
  root 		'pages#home'
  get 		'om-internasjonalen'			        =>	 'pages#about'
  get     'kontakt-internasjonalen'         =>   'pages#kontakt'
  get     'tekniskespsifikasjoner'          =>   'pages#tekniskespsifikasjoner'
  # Endrer "bars" og "bookings" til bar og booking for mer SEO vennelig rute
  get     'bar/:id'                         =>   'bars#show', as: 'bar_show'
  get     'booking/:id'                     =>   'bookings#show', as: 'booking_show'
  # Admin ruter
  get 		'login' 		                      =>	 'sessions#new'
  post		'login' 		                      => 	 'sessions#create'
  delete	'logout'		                      =>	 'sessions#destroy'
  get 		'administrator'	                  =>	 'administrator#index'
  get     'administrator/aldersgrense'      =>   'administrator#aldersgrense'
  get     'administrator/kontaktinfo'       =>   'administrator#kontaktinfo'
  get     'administrator/apningstider'      =>   'administrator#apningstider'
  get     'administrator/hjelp'             =>   'administrator#help'
  get     'administrator/meny'              =>   'administrator#meny'
  get     'administrator/menykategori'      =>   'administrator#menykategori'
  get     'administrator/booking'           =>   'administrator#booking'
  get     'administrator/editbooking'       =>   'administrator#edit_booking'
  get     'administrator/frontpage_images'  =>   'administrator#frontpage_images'
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/tekniskitem.rb
class Tekniskitem < ApplicationRecord
  belongs_to :tekniskcategory, optional: true
  validates :title, presence: true, length: {minimum: 3}
  validates :antall, presence: true, numericality: true
end

app/controllers/tekniskitems_controller.rb
class TekniskitemsController < ApplicationController
  before_action :authenticate_user
  before_action :set_tekniskitem, only: [:show, :edit, :update, :destroy]
  layout 'admin'

  # GET /tekniskitems/1/edit
  def edit
  end

  # POST /tekniskitems
  # POST /tekniskitems.json
  def create
    @tekniskitem = Tekniskitem.new(tekniskitem_params)
      if @tekniskitem.save
        redirect_to tekniskcategories_path , notice: 'Dingsen er lagt til.' 
      else

      end
  end

  # PATCH/PUT /tekniskitems/1
  # PATCH/PUT /tekniskitems/1.json
  def update
      if @tekniskitem.update(tekniskitem_params)
        redirect_to tekniskcategories_path , notice: 'Dingsen er oppdatert.' 
      else

      end
  end

  # DELETE /tekniskitems/1
  # DELETE /tekniskitems/1.json
  def destroy
    @tekniskitem.destroy
      redirect_to tekniskcategories_path , notice: 'Greia er sletta'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tekniskitem
      @tekniskitem = Tekniskitem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tekniskitem_params
      params.require(:tekniskitem).permit(:title, :antall, :tekniskcategory_id, :status)
    end
end

app/helpers/tekniskitems_helper.rb
module TekniskitemsHelper
end

app/views/tekniskitems/_form.html.haml
= form_for @tekniskitem do |f|
  - if @tekniskitem.errors.any? 
    - @tekniskitem.errors.full_messages.each do |error|
      = alert_generator(error) 

  .field
    = f.label :title
    = f.text_field :title
  .field
    = f.label :antall
    = f.number_field :antall
  .field
    = f.label :tekniskcategory
    = f.text_field :tekniskcategory
  .field
    = f.label :status
    = f.text_field :status
  .actions
    = f.submit 'Save'

app/views/tekniskitems/edit.html.haml
%h1 Editing tekniskitem

= render 'form'

= link_to 'Show', @tekniskitem
\|
= link_to 'Back', tekniskitems_path

app/views/tekniskitems/index.html.haml
%h1 Listing tekniskitems

%table
  %thead
    %tr
      %th Title
      %th Antall
      %th Tekniskcategory
      %th Status
      %th
      %th
      %th

  %tbody
    - @tekniskitems.each do |tekniskitem|
      %tr
        %td= tekniskitem.title
        %td= tekniskitem.antall
        %td= tekniskitem.tekniskcategory
        %td= tekniskitem.status
        %td= link_to 'Show', tekniskitem
        %td= link_to 'Edit', edit_tekniskitem_path(tekniskitem)
        %td= link_to 'Destroy', tekniskitem, method: :delete, data: { confirm: 'Are you sure?' }

%br

= link_to 'New Tekniskitem', new_tekniskitem_path

app/views/tekniskitems/new.html.haml
%h1 New tekniskitem

= render 'form'

= link_to 'Back', tekniskitems_path

app/views/tekniskitems/show.html.haml
%p#notice= notice

%p
  %b Title:
  = @tekniskitem.title
%p
  %b Antall:
  = @tekniskitem.antall
%p
  %b Tekniskcategory:
  = @tekniskitem.tekniskcategory
%p
  %b Status:
  = @tekniskitem.status

= link_to 'Edit', edit_tekniskitem_path(@tekniskitem)
\|
= link_to 'Back', tekniskitems_path